### PR TITLE
Add lazy loading rules

### PR DESCRIPTION
**Pull request by reatlat**
@avree would you please check PR, will that work in you r markdown cases?
I found that we can encapsulate JS with `/* <![CDATA[| */` ...  `/* ]]> */` 😎

I also included lazy loading for the form, so that we can load the scripts and form itself when it comes into viewport.

### CODE REVIEW

**Comment by avree** [comment]
Yes, will pull and check later tonight.

**Comment by avree** [comment]
Hmm, it's not loading with this change.

Removed portal/form UUID but otherwise this is my rendered output. Will debug further tomorrow.

`<script type="text/javascript">/<em><![CDATA[\|*/hbspt.forms.create(JSON.parse(decodeURIComponent('%7B%22portalId%22%3A123456%2C%22formId%22%3A%formuuid')))/*]]></em>/</script></p>`

**Comment by reatlat** [comment]
@avree so the inline variation not working on your end 🧐
interesting, do you have some specific settings for markdown-it in your 11ty?

**Comment by reatlat** [comment]
@avree I think I found issue, basically markdown parsing new line character as new paragraphs or something like....
when you have a time, would you test it on your end again?

**Review by zapalblizh — APPROVED** [review]
looks good to me

**Comment by avree** [comment]
> @avree so the inline variation not working on your end 🧐 interesting, do you have some specific settings for markdown-it in your 11ty?

No, I'm not using markdown-it anymore, just 11ty. Your latest update works well.

**Pull request merged**
